version: '3'

services:
  backend:
    build: ./BE/Codedberries/Codedberries
    ports:
      - "8070:8070"  # Map port 8000 of the host to port 8000 of the container


  frontend:
    build: ./FE/angular-app
    ports:
      - "4200:4200"  # Map port 3000 of the host to port 3000 of the container
    depends_on:
      - backend